# Generated by Django 4.1.4 on 2023-01-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=2, null=True)),
                ('telefone', models.CharField(max_length=30, verbose_name='Nº telefone celular')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doutor.agenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'agenda_medico')},
            },
        ),
    ]
